name: flutter_mapbox_blog
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_map: ^1.1.1
  flutter_svg: ^1.1.0
  latlong2: 
  font_awesome_flutter: ^10.5.0
  flutter_screenutil: ^5.8.4
  mapbox_gl: ^0.16.0
  dio: ^5.2.1+1
  geolocator: ^9.0.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
